STYLE_KEYWORDS = {
    "neo-noir",
    "noir",
    "whodunit",
    "reverse chronology",
    "nonlinear timeline",
    "nonlinear narrative",
    "time loop",
    "time travel",
    "psychological thriller",
    "mind-bending",
    "twist ending",
    "unreliable narrator",
    "found footage",
    "mockumentary",
    "slow burn",
    "character study",
    "coming-of-age",
    "surreal",
    "satire",
    "dark comedy",
    "absurdist",
    "minimalist",
    "single location",
    "chamber piece",
    "anthology",
    "episodic",
    "road movie",
    "heist",
    "buddy cop",
    "political thriller",
    "courtroom drama",
    "procedural",
    "mystery",
    "whimsical",
    "romantic comedy",
    "tragicomic",
    "cyberpunk",
    "dystopian",
    "utopian",
    "period piece",
    "historical epic",
    "biopic",
    "documentary-style",
    "experimental",
    "avant-garde",
    "musical",
    "stop motion",
    "animation",
    "superhero",
    "monster movie",
    "kaiju",
    "giallo",
    "slasher",
    "body horror",
    "folk horror",
    "cosmic horror",
    "psychological horror",
    "teen drama",
    "slice of life",
    "sports drama",
}
